name: xconn
base: core22
version: '0.1.0'
summary: WAMP router
description: |
  WAMP router

grade: stable
confinement: strict

apps:
  xconn:
    command: bin/xconn
    completer: bash_autocomplete.sh
    plugs:
      - network
      - network-bind
      - home

parts:
  xconn:
    plugin: go
    source: .
    build-snaps:
      - go
    override-prime: |
      craftctl default
      cp $CRAFT_PART_SRC/bash_autocomplete.sh $CRAFT_PRIME/
